name: test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - uses: leafo/gh-actions-lua@v10
      with:
        lua-version: "5.2.4"

    - name: test
      run: |
        lua test.lua

